import { describe, expect, it } from "vitest";
import {
  releaseMetadata,
  APP_VERSION,
  ENGINE_VERSION,
  OPTIMIZER_VERSION_V4,
  checkEngineCompatibility,
  setActiveSchemaVersion,
} from "../src/version.ts";
import {
  AimLabError,
  toAimLabError,
  guardedWrite,
  persistenceError,
  corruptedDataError,
} from "../src/errors/types.ts";
import { LocalDiagnosticLog } from "../src/diagnostics/localLog.ts";
import { SensitivityOptimizer } from "../src/optimizer/optimizer.ts";
import { buildExperimentDefinition } from "../src/experiments/protocol.ts";

describe("version metadata", () => {
  it("exposes explicit app/engine/optimizer versions", () => {
    const meta = releaseMetadata();
    expect(meta.appVersion).toBe(APP_VERSION);
    expect(meta.engineVersion).toBe(ENGINE_VERSION);
    expect(meta.optimizerVersion).toBe(OPTIMIZER_VERSION_V4);
    expect(meta.schemaVersion).toBeGreaterThanOrEqual(1);
  });

  it("compatibility check rejects newer engine artifacts loudly", () => {
    expect(checkEngineCompatibility(ENGINE_VERSION).compatible).toBe(true);
    expect(checkEngineCompatibility(null).compatible).toBe(true); // legacy data
    const newer = checkEngineCompatibility("engine-v99");
    expect(newer.compatible).toBe(false);
    expect(newer.reason).toMatch(/engine-v99/);
  });

  it("schema version registration validates input", () => {
    setActiveSchemaVersion(1); // restore
    expect(() => setActiveSchemaVersion(0)).toThrow();
    expect(() => setActiveSchemaVersion(2.5)).toThrow();
    setActiveSchemaVersion(1);
  });

  it("recommendations carry engine + app version", () => {
    const definition = buildExperimentDefinition({
      id: "experiment-versioned" as never,
      name: "versioned",
      baselineSensitivity: { sensX: 7, sensY: 7 },
      dpi: 800,
      orderSeed: 3,
      measuredRepsPerCandidatePerRound: 4,
      randomizeOrder: false,
      adaptiveAllocation: { enabled: false },
      stoppingCriteria: { maxSearchRounds: 1 },
    });
    // Minimal synthetic trials through the real pipeline are exercised
    // elsewhere; here we assert the recommendation shell carries versions.
    const optimizer = new SensitivityOptimizer(definition);
    const rec = optimizer.recommend();
    expect(rec.engineVersion).toBe(ENGINE_VERSION);
    expect(rec.appVersion).toBe(APP_VERSION);
  });
});

describe("typed error model", () => {
  it("categorizes errors and keeps user messages safe", () => {
    const err = persistenceError("WRITE_FAILED", "Saving failed. Try again.", {
      path: "trials/x.json",
    });
    expect(err).toBeInstanceOf(AimLabError);
    expect(err.category).toBe("persistence");
    expect(err.retryable).toBe(true);
    expect(err.toJSON().userMessage).not.toMatch(/at .+:\d+/); // no stack leak
  });

  it("corrupted-data errors fail safe and are not retryable", () => {
    const err = corruptedDataError("BAD_ENVELOPE", "This file is damaged.");
    expect(err.failSafeApplied).toBe(true);
    expect(err.retryable).toBe(false);
  });

  it("normalizes unknown thrown values without losing the cause", () => {
    const original = new Error("internal detail with secrets");
    const normalized = toAimLabError(original);
    expect(normalized.category).toBe("user-correctable");
    expect(normalized.userMessage).not.toContain("secrets");
    expect(normalized.cause).toBe(original);

    const passthrough = toAimLabError(persistenceError("X", "known"));
    expect(passthrough.code).toBe("X");
  });

  it("guardedWrite returns typed failures instead of throwing", async () => {
    const ok = await guardedWrite(async () => 42, { kind: "trial-record", path: "t.json" });
    expect(ok.ok).toBe(true);
    expect(ok.value).toBe(42);

    const failed = await guardedWrite<never>(async () => {
      throw new Error("disk full");
    }, { kind: "trial-record", path: "t.json" });
    expect(failed.ok).toBe(false);
    expect(failed.error!.category).toBe("persistence");
    expect(failed.error!.userMessage.length).toBeGreaterThan(0);
  });
});

describe("local diagnostic logging", () => {
  it("records transitions, validation failures, native lifecycle, optimizer summary", () => {
    const log = new LocalDiagnosticLog(() => "2026-01-01T00:00:00Z");
    log.setCaptureMode("native-high-rate @ 1000 Hz");
    log.sessionTransition("setup", "trial-active");
    log.validationFailure("trial-1", ["LARGE_SAMPLE_GAP"]);
    log.nativeLifecycle("connected", { deviceId: "mouse-1" });
    log.optimizerSummary(5600, 0.8, 2);
    log.error("CAPTURE_FAILED", "helper unreachable");

    const bundle = log.exportBundle(["generated by test"]);
    expect(bundle.kind).toBe("aldo-diagnostic-bundle");
    expect(bundle.release.appVersion).toBe(APP_VERSION);
    expect(bundle.captureModeSummary).toContain("1000 Hz");
    const events = bundle.entries.map((e) => e.event);
    expect(events).toEqual([
      "capture-mode",
      "session-transition",
      "validation-failure",
      "native-lifecycle",
      "optimizer-summary",
      "error",
    ]);
    expect(bundle.notes).toEqual(["generated by test"]);
  });

  it("rotates entries beyond the in-memory cap deterministically", () => {
    const log = new LocalDiagnosticLog(() => "2026-01-01T00:00:00Z");
    for (let i = 0; i < 2500; i++) log.log("info", "tick", { i });
    const entries = log.entries();
    expect(entries.length).toBeLessThanOrEqual(2000);
    expect(entries[0]!.seq).toBe(0);
    expect(entries[entries.length - 1]!.detail.i).toBe(2499);
  });
});
